// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.PillPressRegistry.Interfaces
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Inspectionprocessflowworkflowlogs.
    /// </summary>
    public static partial class InspectionprocessflowworkflowlogsExtensions
    {
            /// <summary>
            /// Get bcgov_inspectionprocessflow_WorkflowLogs from
            /// bcgov_inspectionprocessflows
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='businessprocessflowinstanceid'>
            /// key: businessprocessflowinstanceid of bcgov_inspectionprocessflow
            /// </param>
            /// <param name='top'>
            /// </param>
            /// <param name='skip'>
            /// </param>
            /// <param name='search'>
            /// </param>
            /// <param name='filter'>
            /// </param>
            /// <param name='count'>
            /// </param>
            /// <param name='orderby'>
            /// Order items by property values
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            public static MicrosoftDynamicsCRMworkflowlogCollection Get(this IInspectionprocessflowworkflowlogs operations, string businessprocessflowinstanceid, int? top = default(int?), int? skip = default(int?), string search = default(string), string filter = default(string), bool? count = default(bool?), IList<string> orderby = default(IList<string>), IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>))
            {
                return operations.GetAsync(businessprocessflowinstanceid, top, skip, search, filter, count, orderby, select, expand).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get bcgov_inspectionprocessflow_WorkflowLogs from
            /// bcgov_inspectionprocessflows
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='businessprocessflowinstanceid'>
            /// key: businessprocessflowinstanceid of bcgov_inspectionprocessflow
            /// </param>
            /// <param name='top'>
            /// </param>
            /// <param name='skip'>
            /// </param>
            /// <param name='search'>
            /// </param>
            /// <param name='filter'>
            /// </param>
            /// <param name='count'>
            /// </param>
            /// <param name='orderby'>
            /// Order items by property values
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<MicrosoftDynamicsCRMworkflowlogCollection> GetAsync(this IInspectionprocessflowworkflowlogs operations, string businessprocessflowinstanceid, int? top = default(int?), int? skip = default(int?), string search = default(string), string filter = default(string), bool? count = default(bool?), IList<string> orderby = default(IList<string>), IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(businessprocessflowinstanceid, top, skip, search, filter, count, orderby, select, expand, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get bcgov_inspectionprocessflow_WorkflowLogs from
            /// bcgov_inspectionprocessflows
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='businessprocessflowinstanceid'>
            /// key: businessprocessflowinstanceid of bcgov_inspectionprocessflow
            /// </param>
            /// <param name='workflowlogid'>
            /// key: workflowlogid of workflowlog
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            public static MicrosoftDynamicsCRMworkflowlog WorkflowLogsByKey(this IInspectionprocessflowworkflowlogs operations, string businessprocessflowinstanceid, string workflowlogid, IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>))
            {
                return operations.WorkflowLogsByKeyAsync(businessprocessflowinstanceid, workflowlogid, select, expand).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get bcgov_inspectionprocessflow_WorkflowLogs from
            /// bcgov_inspectionprocessflows
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='businessprocessflowinstanceid'>
            /// key: businessprocessflowinstanceid of bcgov_inspectionprocessflow
            /// </param>
            /// <param name='workflowlogid'>
            /// key: workflowlogid of workflowlog
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<MicrosoftDynamicsCRMworkflowlog> WorkflowLogsByKeyAsync(this IInspectionprocessflowworkflowlogs operations, string businessprocessflowinstanceid, string workflowlogid, IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.WorkflowLogsByKeyWithHttpMessagesAsync(businessprocessflowinstanceid, workflowlogid, select, expand, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
