// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.PillPressRegistry.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// msdyn_account_knowledgebaserecord
    /// </summary>
    public partial class MicrosoftDynamicsCRMmsdynAccountKnowledgebaserecord
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMmsdynAccountKnowledgebaserecord class.
        /// </summary>
        public MicrosoftDynamicsCRMmsdynAccountKnowledgebaserecord()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMmsdynAccountKnowledgebaserecord class.
        /// </summary>
        public MicrosoftDynamicsCRMmsdynAccountKnowledgebaserecord(long? versionnumber = default(long?), string knowledgebaserecordid = default(string), string msdynAccountKnowledgebaserecordid = default(string), string accountid = default(string))
        {
            Versionnumber = versionnumber;
            Knowledgebaserecordid = knowledgebaserecordid;
            MsdynAccountKnowledgebaserecordid = msdynAccountKnowledgebaserecordid;
            Accountid = accountid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "versionnumber")]
        public long? Versionnumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "knowledgebaserecordid")]
        public string Knowledgebaserecordid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "msdyn_account_knowledgebaserecordid")]
        public string MsdynAccountKnowledgebaserecordid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountid")]
        public string Accountid { get; set; }

    }
}
