// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.PillPressRegistry.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Microsoft.Dynamics.CRM.bcgov_investigationstep_cecontact
    /// </summary>
    public partial class MicrosoftDynamicsCRMbcgovInvestigationstepCecontact
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMbcgovInvestigationstepCecontact class.
        /// </summary>
        public MicrosoftDynamicsCRMbcgovInvestigationstepCecontact()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMbcgovInvestigationstepCecontact class.
        /// </summary>
        public MicrosoftDynamicsCRMbcgovInvestigationstepCecontact(string versionnumber = default(string), string bcgovCecontactid = default(string), string bcgovInvestigationstepCecontactid = default(string), string bcgovInvestigationstepid = default(string))
        {
            Versionnumber = versionnumber;
            BcgovCecontactid = bcgovCecontactid;
            BcgovInvestigationstepCecontactid = bcgovInvestigationstepCecontactid;
            BcgovInvestigationstepid = bcgovInvestigationstepid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "versionnumber")]
        public string Versionnumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bcgov_cecontactid")]
        public string BcgovCecontactid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bcgov_investigationstep_cecontactid")]
        public string BcgovInvestigationstepCecontactid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bcgov_investigationstepid")]
        public string BcgovInvestigationstepid { get; set; }

    }
}
