// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.PillPressRegistry.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// bcgov_inspection_actregulationref
    /// </summary>
    public partial class MicrosoftDynamicsCRMbcgovInspectionActregulationref
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMbcgovInspectionActregulationref class.
        /// </summary>
        public MicrosoftDynamicsCRMbcgovInspectionActregulationref()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMbcgovInspectionActregulationref class.
        /// </summary>
        public MicrosoftDynamicsCRMbcgovInspectionActregulationref(long? versionnumber = default(long?), string bcgovActregulationreferenceid = default(string), string bcgovInspectionActregulationrefid = default(string), string bcgovInspectionid = default(string))
        {
            Versionnumber = versionnumber;
            BcgovActregulationreferenceid = bcgovActregulationreferenceid;
            BcgovInspectionActregulationrefid = bcgovInspectionActregulationrefid;
            BcgovInspectionid = bcgovInspectionid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "versionnumber")]
        public long? Versionnumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bcgov_actregulationreferenceid")]
        public string BcgovActregulationreferenceid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bcgov_inspection_actregulationrefid")]
        public string BcgovInspectionActregulationrefid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bcgov_inspectionid")]
        public string BcgovInspectionid { get; set; }

    }
}
