// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.PillPressRegistry.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Collection of bcgov_investigation_cecontact
    /// </summary>
    /// <remarks>
    /// Microsoft.Dynamics.CRM.bcgov_investigation_cecontactCollection
    /// </remarks>
    public partial class MicrosoftDynamicsCRMbcgovInvestigationCecontactCollection
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMbcgovInvestigationCecontactCollection class.
        /// </summary>
        public MicrosoftDynamicsCRMbcgovInvestigationCecontactCollection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMbcgovInvestigationCecontactCollection class.
        /// </summary>
        public MicrosoftDynamicsCRMbcgovInvestigationCecontactCollection(IList<MicrosoftDynamicsCRMbcgovInvestigationCecontact> value = default(IList<MicrosoftDynamicsCRMbcgovInvestigationCecontact>))
        {
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<MicrosoftDynamicsCRMbcgovInvestigationCecontact> Value { get; set; }

    }
}
