// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.PillPressRegistry.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Collection of bcgov_complaint
    /// </summary>
    /// <remarks>
    /// Microsoft.Dynamics.CRM.bcgov_complaintCollection
    /// </remarks>
    public partial class MicrosoftDynamicsCRMbcgovComplaintCollection
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMbcgovComplaintCollection class.
        /// </summary>
        public MicrosoftDynamicsCRMbcgovComplaintCollection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMbcgovComplaintCollection class.
        /// </summary>
        public MicrosoftDynamicsCRMbcgovComplaintCollection(IList<MicrosoftDynamicsCRMbcgovComplaint> value = default(IList<MicrosoftDynamicsCRMbcgovComplaint>))
        {
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<MicrosoftDynamicsCRMbcgovComplaint> Value { get; set; }

    }
}
